#!/usr/bin/env bash
# Affiché par : make test-help
set -e
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
cd "$DOTFILES_DIR" 2>/dev/null || true

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Tests dotfiles — variables, bac à sable, Makefile"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1) Filtrer les managers à tester (Docker)"
echo "   ─────────────────────────────────────"
echo "   DOTFILES_TEST_MANAGERS   liste avec virgules ou espaces (recommandé)"
echo "   TEST_MANAGERS            même rôle ; prioritaire si les deux sont posés"
echo ""
echo "   Exemples :"
echo "     DOTFILES_TEST_MANAGERS=pathman,installman,searchman make test"
echo "     TEST_MANAGERS=\"pathman installman\" make test-subcommands"
echo "     TEST_SHELLS=zsh DOTFILES_TEST_MANAGERS=netman make test"
echo ""
echo "2) Fichier local (non versionné)"
echo "   ────────────────────────────────"
echo "   cp scripts/test/config/test.local.env.example scripts/test/config/test.local.env"
echo "   # puis éditer : TEST_SHELLS, TEST_MANAGERS, SUBCOMMAND_TIER, TEST_DOTFILES_ISOLATE=1, …"
echo "   DOTFILES_TEST_USER_ENV=/chemin/custom.env  make test"
echo ""
echo "3) Bac à sable « live » (shell dans le conteneur)"
echo "   ───────────────────────────────────────────────"
echo "   make docker-in              # zsh par défaut"
echo "   make docker-in DOCKER_SHELL=bash"
echo "   Dans le conteneur : source \$DOTFILES_DIR/zsh/zshrc_custom"
echo "   Doc détaillée :     cat scripts/test/SANDBOX.md"
echo ""
echo "4) Autres cibles utiles"
echo "   ───────────────────"
echo "   make tests              # menu interactif des tests"
echo "   make test-checks        # syntaxe cores + adapters + URLs (local ou CI)"
echo "   sh scripts/test/installman_check.sh"
echo "   bash scripts/test/verify_multishell.sh"
echo ""
echo "5) Liste par défaut des managers pour « make test »"
echo "   ───────────────────────────────────────────────"
echo "   scripts/test/config/migrated_managers.list"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
