#!/usr/bin/env bash
# Affiché par : make test-help
set -e
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
cd "$DOTFILES_DIR" 2>/dev/null || true

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Tests dotfiles — variables, bac à sable, Makefile"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1) Filtrer les managers à tester (Docker)"
echo "   ─────────────────────────────────────"
echo "   DOTFILES_TEST_MANAGERS   liste avec virgules ou espaces (recommandé)"
echo "   TEST_MANAGERS            même rôle ; prioritaire si les deux sont posés"
echo ""
echo "   Exemples :"
echo "     DOTFILES_TEST_MANAGERS=pathman,installman,searchman make test"
echo "     TEST_MANAGERS=\"pathman installman\" make test-subcommands"
echo "     TEST_SHELLS=zsh DOTFILES_TEST_MANAGERS=netman make test"
echo ""
echo "2) Fichier local (non versionné)"
echo "   ────────────────────────────────"
echo "   cp scripts/test/config/test.local.env.example scripts/test/config/test.local.env"
echo "   # puis éditer : TEST_SHELLS, TEST_MANAGERS, SUBCOMMAND_TIER, TEST_DOTFILES_ISOLATE=1, …"
echo "   DOTFILES_TEST_USER_ENV=/chemin/custom.env  make test"
echo ""
echo "3) Bac à sable « live » (shell dans le conteneur)"
echo "   ───────────────────────────────────────────────"
echo "   make docker-in              # menus distro + shell si terminal ; sinon Arch + zsh"
echo "   make docker-in DOCKER_DISTRO=debian DOCKER_SHELL=fish   # forcer sans menus"
echo "   Distros : arch (image docker-build), ubuntu, debian, alpine, fedora, centos, opensuse, gentoo (build long)"
echo "   Sans export manuel : DOCKER_DOTFILES_DIR, DOCKER_INSTALLMAN_ASSUME (voir Makefile / docker_in.sh)"
echo "   Confirmations installman :  make docker-in DOCKER_INSTALLMAN_ASSUME=0"
echo "   Dans le conteneur : root par défaut ; source \$DOTFILES_DIR/zsh/zshrc_custom si besoin"
echo "   Doc détaillée :     cat scripts/test/SANDBOX.md"
echo ""
echo "   Smoke vs assertions métier : make test / matrice = surtout « ne plante pas / timeout » ; assertions"
echo "   ciblées (golden, grep) = évolution — voir TODOS.md § « Phase A — tests »."
echo ""
echo "4) Autres cibles utiles"
echo "   ───────────────────"
echo "   make tests              # menu interactif des tests"
echo "   DOTFILES_TEST_MENU_SKIP_PAUSE=1 make tests   # pas de pause « Entrée » après chaque action"
echo "   make test-checks        # syntaxe cores + adapters + URLs (local ou CI)"
echo "   make test-dotfiles-good # bac à sable DOTFILES_GOOD/ (smoke POSIX, additif)"
echo "   sh scripts/test/installman_check.sh"
echo "   bash scripts/test/verify_multishell.sh"
echo ""
echo "5) Liste par défaut des managers pour « make test »"
echo "   ───────────────────────────────────────────────"
echo "   scripts/test/config/migrated_managers.list"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
